[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "st-paywall"
version = "0.1.2"
description = "A Python package for creating subscription Streamlit apps"
authors = [
    {name = "Tyler", email = "tylerjrichards@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
dependencies = [
    "stripe",
    "httpx-oauth",
    "pyjwt"
]




